version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  weather-monitor:
    build:
      context: ./weather-monitor
      dockerfile: dockerfile
    restart: "no"
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
    ports:
      - '8080:8080'
    depends_on:
      - db

  ingestion:
    build:
      context: ./ingestion
      dockerfile: dockerfile
    restart: "no"
    ports:
      - '8081:8081'
    depends_on:
      - weather-monitor

  weather-generator:
    build:
      context: ./weather-generator
      dockerfile: dockerfile
    restart: "no"
    environment:
      INGESTION_SERVICE_DOMAIN: ingestion
      INGESTION_SERVICE_PORT: 8081
    ports:
      - '8082:8082'
    depends_on:
      - ingestion



