###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "firstname": "test_fa4e6329afe9",
  "lastname": "test_9d0893c18c98",
  "email": "test_4609cbdcc160",
  "password": "test_0d1b253cf339"
}

<> 2023-03-20T202050.200.json

###
POST http://localhost:8082/auth/authenticate
Content-Type: application/json

{
  "email": "test_4609cbdcc160",
  "password": "test_0d1b253cf339"
}

<> 2023-03-20T202330.200.json